# Generated by Django 6.1.1 on 2026-09-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=200, verbose_name='Posisi')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Pekerjaan')),
                ('kualifikasi', models.TextField(verbose_name='Kualifikasi')),
                ('keterampilan_dibutuhkan', models.TextField(help_text='Pisahkan dengan koma. Contoh: Python, Django, SQL', verbose_name='Keterampilan yang Dibutuhkan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Lowongan',
                'verbose_name_plural': 'Lowongan',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
