# Generated by Django 6.1.1 on 2026-09-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_cv', models.FileField(upload_to='cv_uploads/', verbose_name='File CV (PDF/DOCX)')),
                ('nama_file', models.CharField(blank=True, max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('sudah_diparse', models.BooleanField(default=False)),
                ('pelamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
                'ordering': ['-diunggah_pada'],
            },
        ),
        migrations.CreateModel(
            name='HasilParsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(blank=True, max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nomor_telepon', models.CharField(blank=True, max_length=30, verbose_name='No. Telepon')),
                ('skill_terdeteksi', models.TextField(blank=True, verbose_name='Skill Terdeteksi')),
                ('riwayat_kerja', models.TextField(blank=True, verbose_name='Riwayat Kerja')),
                ('pendidikan', models.TextField(blank=True, verbose_name='Pendidikan')),
                ('teks_mentah', models.TextField(blank=True, verbose_name='Teks Mentah CV')),
                ('diparse_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_parsing', to='resume.cv')),
            ],
            options={
                'verbose_name': 'Hasil Parsing CV',
                'verbose_name_plural': 'Hasil Parsing CV',
            },
        ),
    ]
